### ISSUE TITLE
Multiple Queue Support

### ISSUE THREAD

**Issue by mattdonatelli** [kazubot/kazubot#4]
Make queues a Class and be able to instantiate multiples by dodocode.

**Comment by Menyueru** [comment]
Wouldn't having them by channels be easier? Specially since people could forget what is the Dodo Code of the queue they are trying to get into, or mistype it

**Comment by mattdonatelli** [comment]
I'd like the system to be smart enough to know how many queues are open in a given channel. That way users only have to specify dodocode to join if there's more than one queue open in a channel. If they try k!join without an argument specified and there are two or more queues open, kazubot should respond with a "which queue did you want to join?" and show a list of queues by host and dodo code.

**Comment by Menyueru** [comment]
Ok that sounds understandable I imagine mistyping should result in a similar behaviour then

**Comment by mattdonatelli** [comment]
> 
> 
> Wouldn't having them by channels be easier? Specially since people could forget what is the Dodo Code of the queue they are trying to get into, or mistype it

Actually this makes a lot more sense, as multiple queues in the same channel would be very noisy. I think I might look into taking it in this direction soon :)
