### ISSUE TITLE
Improve k!join for Turnips in inventory Y/N interaction

### ISSUE THREAD

**Issue by mattdonatelli** [kazubot/kazubot#6]
Would be nice if k!join were broken up so that the bot asks the person if they have turnips ready or not, and only lets them join if they respond with yes. (Can this be done via an emoji reaction? Because that would be dope)

**Comment by debbytam** [comment]
ooh yes i was looking at reactions before. 
wondering if putting this prompt at the k!join level is too early?  could possibly prompt people as their turn is coming up ? maybe the third person in line

**Comment by mattdonatelli** [comment]
I've noticed this is actually an issue with the 1st person to join the queue sometimes. What'll happen is a host will open their island, and then people will rush to join before they are ready, holding up the flow of traffic on that 1st person who may or may not be faster at getting their turnips than other folks. Hopefully by the 3rd or 4th person this reminder won't be necessary.
